### ISSUE TITLE
Realtime metrics

### ISSUE THREAD

**Issue by timgent** [UKHomeOffice/engineering-and-architecture#11]
We want to be able to quickly see how projects are performing, and be able to aggregate these to see how we are performing across the whole of our IT estate. Thoughts are welcome

**Comment by shabe** [comment]
Here's a quick starter from me:

Three categories:

- **System Level Metrics** (stuff the dev teams care about)
- Host / Container health, performance, response time etc  (sysdig / other)
- Codebase health (sonarqube / cast / other, trend over time)
- % of failed deployments (mapped from ServiceNow, trend over time)
- lead time, how long from change to production  (github, gitlab)

**Business Level Metrics** (stuff the business / product managers care about)

- Current users on the service or business specific (time series)
- Project costs (for charge-back, pull from AWS, tags etc)
- Service availability (up/down traffic lights)
- Recent changes deployed (last change, link to stories)
- Change frequency (deployments per day, features per week etc)
- Current Open incidents (P1, P2, mapped from ServiceNow)
- Current Open customer issues (P3, mapped from ServiceNow or JIRA or other)

Policy Level Metrics (stuff the service owner / minister cares about)

- ???

**Comment by Abdul2** [comment]
i suggest we include a 4th category to show delivery against expectations

**Comment by shabe** [comment]
@Abdul2 Would that be a Business Level metric?

**Comment by danielepolencic** [comment]
This ticket moved to: https://github.com/UKHomeOffice/engineering-and-architecture-board/issues/238
