### ISSUE TITLE
Fill in overview sections on TCOP

### ISSUE THREAD

**Issue by timgent** [UKHomeOffice/engineering-and-architecture#13]
This includes the Summary in the main README.md, and the Background, Context, and Scope of the TCOP (put these into a new file and make sure the link from the main README works)

@gabbym54 I've assigned you to this let me know if this is ok (or not!). Happy to help out especially with workings of Github Markdown docs - just give me or one of the other devs a shout

**Comment by GrahamR-HO** [comment]
We have defined TCOP ownership & target audience (as per workshops) - suggest these are added to the scope/background of the TCOP, this may also impact main headings/focus.

Outputs: Ownership & Target Audience:

**TCoP Ownership**
- Head of Engineering and Architecture

**Target Audience**

- Technologist (Software Engineers, DevOp Engineers, Architects)
- Wider DDaT (incl, technologist, SMT)
- Commercial 
- Legal
- Client side suppliers
- Outsourced suppliers
- Recruiters
-

**Comment by danielepolencic** [comment]
This ticket was moved to: https://github.com/UKHomeOffice/engineering-and-architecture-board/issues/237
