### ISSUE TITLE
Privacy of this board

### ISSUE THREAD

**Issue by GrahamR-HO** [UKHomeOffice/engineering-and-architecture#14]
Do we have clear guidance on what we can and cannot put in public domain? Preference would be for private as default, then a controlled process (governance) on migrating content to a public board.

**Comment by GrahamR-HO** [comment]
In the absence of any feedback on this issue - please make this board private, until we can have the discussion.

Note: Besides the obvious security/sensitivity issues; we do need to be mindful of the organisational/professional image we portray and any reputational damage (indirectly) that exists by publishing directly into the public domain without the appropriate controls in place. We are currently publishing a very early drafts of our content and/or content with numerous broken links.

**Comment by danielepolencic** [comment]
moved to: https://github.com/UKHomeOffice/engineering-and-architecture-board/issues/249
