### ISSUE TITLE
changing the landing page of the engineering and architecture repo

### ISSUE THREAD

**Issue by Abdul2** [UKHomeOffice/engineering-and-architecture#19]
![screen shot 2017-05-17 at 14 15 12](https://cloud.githubusercontent.com/assets/9384464/26155663/e13dacf0-3b0b-11e7-9948-d68769937026.jpg)

I would like to propose changes to the landing page so that it shows folders as supposed to .md files (to make it neater)

**Comment by danielepolencic** [comment]
moved to: https://github.com/UKHomeOffice/engineering-and-architecture-board/issues/247
