### ISSUE TITLE
No Context or Scope defined

### ISSUE THREAD

**Issue by GrahamR-HO** [UKHomeOffice/engineering-and-architecture#25]
We have some elements of the context and scope defined from the workshop sessions - please refer back to these. 

Anyone engaging with COE must understand the context and scope of the TCOP; these are key items and should be main page items.

**Comment by danielepolencic** [comment]
Is this the same as https://github.com/UKHomeOffice/engineering-and-architecture-board/issues/237?

**Comment by GrahamR-HO** [comment]
Yes please combine these. thanks

**Comment by danielepolencic** [comment]
moved to: https://github.com/UKHomeOffice/engineering-and-architecture-board/issues/237
