### ISSUE TITLE
Principles: Where possible, each principle to have an objective measurement.

### ISSUE THREAD

**Issue by GrahamR-HO** [UKHomeOffice/engineering-and-architecture#8]
To enable good governance/assurance process, principles should provide guidance on objective measurements + examples (if poss).

**Comment by GrahamR-HO** [comment]
examples of measures/rationale can be located in DDaT Confluence - https://collaboration.homeoffice.gov.uk/display/HOA/Principles

https://collaboration.homeoffice.gov.uk/display/HOA/Principle+S4%3A+Services+are+loosely+coupled

**Comment by danielepolencic** [comment]
moved to: https://github.com/UKHomeOffice/engineering-and-architecture-board/issues/239
