### ISSUE TITLE
TCOP: Create TCOP skeleton - Identifying headings/ subheadings

### ISSUE THREAD

**Issue by GrahamR-HO** [UKHomeOffice/engineering-and-architecture#9]

**Comment by GrahamR-HO** [comment]
Abdul and Jerry have available draft TCOP skeleton / signposting.

**Comment by timgent** [comment]
@gabbym54 Let me know when you're around next week to do this

**Comment by gabbym54** [comment]
@timgent  will send you my calendar to your digital account :)

**Comment by timgent** [comment]
Update - Abdul, Gabby, and I had a catch up and came up with a straw man. I will put in a PR to this repo soon to get the structure in and send around so everyone can comment

**Comment by GrahamR-HO** [comment]
Reopening this issue as TCOP top level + sub headings have not been fully clarified amongst team.

**Comment by danielepolencic** [comment]
moved to: https://github.com/UKHomeOffice/engineering-and-architecture-board/issues/250
